export const projects = [
    { 
        id: 1,
        title: "Acme Store - Modern Ecommerce",
        link: "https://demo.vercel.store/",
        thumbnail: "/acme.png",
        description: "Blazingly Fast Ecom Store",
        isFeatured: true,
    },
    { 
        id: 2,
        title: "Design World — An Ecommerce Brand",
        link: "https://design-world.vercel.app",
        thumbnail: "/design-world.png",
        description: "Design World is merchandise brand, curated by their own customers.",
        isFeatured: true,
    },
    { 
        id: 3,
        title: "JK Adventure - A Travel Agency",
        link: "https://jk-adventure.vercel.app",
        thumbnail: "/jk-adventure.png",
        description: "Travel, Adventure",
        isFeatured: true,
    },
    { 
        id: 4,
        title: "Kapda Factory - Clothing Brand",
        link: "https://kapdafactory.in/",
        thumbnail: "/kapda-factory.png",
        description: "Clothing - Apparel",
        isFeatured: true,
    },
    { 
        id: 5,
        title: "Pandey Tuitions",
        link: "https://pandeytuitions.vercel.app/",
        thumbnail: "/pandey-tuitions.png",
        description: "Edtech, Education, Courses",
        isFeatured: false,
    },
    { 
        id: 6,
        title: "Girja Masala",
        link: "https://girja-masala.vercel.app",
        thumbnail: "/girja-masala.png",
        description: "Ecommerce, Store",
        isFeatured: false,
    },
    { 
        id: 7,
        title: "Wevstack",
        link: "https://wevstack.vercel.app",
        thumbnail: "/wevstack.png",
        description: "Tools, Portfolio",
        isFeatured: false,
    },
    // { 
    //     id: 8,
    //     title: "Kapda Factory - Clothing Brand",
    //     link: "https://kapdafactory.in/",
    //     thumbnail: "/project-7.png",
    //     description: "Clothing - Apparel",
    // isFeatured: true,
    // },
]